# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe01e232b2db25dd34085602590bd82eaae206d157a8e838cf810eef2b64d3d4c02f2d7fad8e3bf959d4840c76262f78753de04696e1f80cccb7aca529bad67

test:
  secret_key_base: 6486f5d3afb50ff7984d4546386bf45e3c6ffe29e45276b54aa2be350ff39ada71c3041afeeae3c0d0f49c9be7cd06d798a4513148e449ea408d282edbf1c274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
